In [1]:
import pandas as pd

dados = {
    'tipo_quarto':['Standart', 'Standart', 'Solteiro', 'Duplo', 'Superior',
                   'Executivo', 'Master', 'Suite Junior', 'Villa', 'Villa'
                   ],
    'dia_semana':['Segunda', 'Segunda', 'Quarta', 'Quinta','Sexta','Sabado', 'Domingo', 'Domingo', 'Domingo', 'Domingo'],
    'reservas':[10, 8, 9, 14, 34, 38, 61, 56, 28, 34]
}
df = pd.DataFrame(dados)
df

    tipo_quarto dia_semana  reservas
0      Standart    Segunda        10
1      Standart    Segunda         8
2      Solteiro     Quarta         9
3         Duplo     Quinta        14
4      Superior      Sexta        34
5     Executivo     Sabado        38
6        Master    Domingo        61
7  Suite Junior    Domingo        56
8         Villa    Domingo        28
9         Villa    Domingo        34

In [2]:
df_pivot_table = df.pivot_table(
    index=['tipo_quarto'],
    columns=['dia_semana'],
    values=['reservas'],
    aggfunc='mean'
)
df_pivot_table

             reservas
dia_semana    Domingo Quarta Quinta Sabado Segunda Sexta
tipo_quarto
Duplo             NaN    NaN   14.0    NaN     NaN   NaN
Executivo         NaN    NaN    NaN   38.0     NaN   NaN
Master           61.0    NaN    NaN    NaN     NaN   NaN
Solteiro          NaN    9.0    NaN    NaN     NaN   NaN
Standart          NaN    NaN    NaN    NaN     9.0   NaN
Suite Junior     56.0    NaN    NaN    NaN     NaN   NaN
Superior          NaN    NaN    NaN    NaN     NaN  34.0
Villa            31.0    NaN    NaN    NaN     NaN   NaN