In [1]:
import pandas as pd

report = {
    'vendedor': ['Pedro', 'Pedro', 'Thomas', 'Peter', 'Freddy',
                 'Alexander', 'Ronald', 'Vicent', 'Vincent','Mariah'
                 ],
    'mes': [1, 1, 2, 3, 4, 5, 6, 7, 7, 8],
    'valor_vendido': [3451, 3716, 4629, 3528, 3281,
                      3971, 2869, 2918, 3989, 3018]
}
df = pd.DataFrame(report)
df

    vendedor  mes  valor_vendido
0      Pedro    1           3451
1      Pedro    1           3716
2     Thomas    2           4629
3      Peter    3           3528
4     Freddy    4           3281
5  Alexander    5           3971
6     Ronald    6           2869
7     Vicent    7           2918
8    Vincent    7           3989
9     Mariah    8           3018

In [3]:
df_pivot_table = df.pivot_table(
    index=['vendedor'],
    columns=['mes'],
    values=['valor_vendido'],
    aggfunc='sum'
)
df_pivot_table

          valor_vendido                                                  \
mes                   1       2       3       4       5       6       7
vendedor
Alexander           NaN     NaN     NaN     NaN  3971.0     NaN     NaN
Freddy              NaN     NaN     NaN  3281.0     NaN     NaN     NaN
Mariah              NaN     NaN     NaN     NaN     NaN     NaN     NaN
Pedro            7167.0     NaN     NaN     NaN     NaN     NaN     NaN
Peter               NaN     NaN  3528.0     NaN     NaN     NaN     NaN
Ronald              NaN     NaN     NaN     NaN     NaN  2869.0     NaN
Thomas              NaN  4629.0     NaN     NaN     NaN     NaN     NaN
Vicent              NaN     NaN     NaN     NaN     NaN     NaN  2918.0
Vincent             NaN     NaN     NaN     NaN     NaN     NaN  3989.0


mes             8
vendedor
Alexander     NaN
Freddy        NaN
Mariah     3018.0
Pedro         NaN
Peter         NaN
Ronald        NaN
Thomas        NaN
Vicent        NaN
Vincent       NaN