In [1]:
import pandas as pd

In [37]:
df = pd.DataFrame({
    'seller':['Luiz ', 'pEdro','fernanda', 'fernanda'],
    'product':['Celular', 'Tv', 'Sofa', 'Sofa' ],
    'value':['R$ 1.200,00', '850.00', '4.500,00', '4.500,00'],
    'sale_date':['2020-15-29', '2025/09/10', '09-10-2025', '09-10-2025']
})

In [38]:
df

     seller  product        value   sale_date
0     Luiz   Celular  R$ 1.200,00  2020-15-29
1     pEdro       Tv       850.00  2025/09/10
2  fernanda     Sofa     4.500,00  09-10-2025
3  fernanda     Sofa     4.500,00  09-10-2025

In [39]:
df['seller'] = (
    df['seller']
    .str.split()
    .str.join(" ")
    .str.title()
)

In [40]:
def clear_price(value):
    if ',' in value:
        value = value.replace('.', '')  #1200,00
        value = value.replace(',', '.')  #1200.00
    if 'R$' in value:
        value = value.replace('R$', '')
    else:
        value = value
    return value

In [43]:
df['value'] = df['value'].apply(clear_price)
df['sale_date'] = df['sale_date'].str.replace('/', '-')

In [42]:
df.loc[df['sale_date'] == '09-10-2025', 'sale_date'] = '2025-10-09'

Conversão de número

In [45]:
df['value'] = pd.to_numeric(df['value'], errors='coerce')

Conversão para DateTime

In [51]:
df['sale_date'] = pd.to_datetime(df['sale_date'], format='%Y-%m-%d', errors='coerce')

In [50]:
print(df['sale_date'].isna().sum())

1

In [52]:
print(df)

     seller  product   value  sale_date
0      Luiz  Celular  1200.0        NaT
1     Pedro       Tv   850.0 2025-09-10
2  Fernanda     Sofa  4500.0 2025-10-09
3  Fernanda     Sofa  4500.0 2025-10-09

Removendo colunas duplicadas

In [53]:
df.duplicated(subset=['seller', 'product', 'sale_date'], keep='last')

0    False
1    False
2     True
3    False
dtype: bool

In [54]:
df.drop_duplicates(subset=['seller', 'product', 'sale_date'], keep='last')

     seller  product   value  sale_date
0      Luiz  Celular  1200.0        NaT
1     Pedro       Tv   850.0 2025-09-10
3  Fernanda     Sofa  4500.0 2025-10-09