In [6]:
import pandas as pd

In [15]:
df = pd.read_csv(r"C:\Users\ruans\OneDrive\Documentos\Material curso engenharia de dados\Python+-+SGBDS\Arquivos\05.+SQL+Server\05. SQL Server\Origem\Origem\arquivos_csv\Clientes.csv", delimiter=',')
df.head()

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12

In [8]:
# Filtrar 1 item especifico de uma coluna
estado = df.loc[df['state'] == 'Mato Grosso']

In [11]:
estado

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
12,12,2018-03-28 00:24:00,Carol,Barboza,carol@exemplo.com,9 8487-3501,Brasil,Mato Grosso,Rua 31 do Estado Mato Grosso,1.0,Conjunto 23
15,15,2018-11-15 18:00:53,Stephanie,Barbosa,stephanie@usuario.com,9 1446-3560,Brasil,Mato Grosso,NaN,NaN,Conjunto 4
66,66,2018-10-18 04:31:59,Stephanie,Abreu,stephanie@meu_email.com,9 6466-2389,Brasil,Mato Grosso,Rua 19 do Estado Mato Grosso,53.0,Conjunto 13
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN

In [10]:
# escolher estados especifícos
estados = ['Rio de Janeiro', 'Ceará', 'Rondônia', 'Bahia']
Df_estados = df.loc[df['state'].isin(estados)]
Df_estados

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
21,21,2018-02-21 15:35:55,Diego,Freire,diego@teste.com,9 6686-4094,Brasil,Bahia,Praça 4 do Estado Bahia,906.0,Apto 20
24,24,2018-07-25 09:34:12,Jair,Barroso,jair@teste.com,9 6679-6120,Brasil,Ceará,Rua 86 do Estado Ceará,770.0,Apto 21
32,32,2018-07-22 11:59:27,Ana,Campos,ana@teste.com,9 1932-9841,Brasil,Bahia,Avenida 52 do Estado Bahia,402.0,NaN
43,43,2018-01-07 07:54:22,Daniela,Lima,NaN,9 1763-2584,Brasil,Rio de Janeiro,NaN,NaN,Apto 20
47,47,2018-09-01 23:00:40,Júlia,Castro,júlia@exemplo.com,9 7096-1780,Brasil,Rio de Janeiro,Rua 39 do Estado Rio de Janeiro,983.0,Conjunto 7
48,48,2018-05-29 04:22:54,Clarissa,Albuquerque,clarissa@exemplo.com,9 7403-4273,Brasil,Ceará,NaN,NaN,Apto 12
49,49,2018-11-01 02:13:51,Júlia,Sousa,júlia@exemplo.com,9 2094-8467,Brasil,Rondônia,Rua 12 do Estado Rondônia,260.0,Apto 27
55,55,2018-07-10 18:40:07,Gabriela,Pires,gabriela@meu_email.com,9 1214-1539,Brasil,Rio de Janeiro,Rua 32 do Estado Rio de Janeiro,838.0,Apto 29
58,58,2018-09-13 03:13:02,Rafael,Rodrigues,rafael@meu_email.com,9 6550-3557,Brasil,Bahia,Praça 94 do Estado Bahia,647.0,Apto 25
63,63,2018-05-05 17:52:26,Caíque,Batista,caíque@teste.com,9 8818-5886,Brasil,Ceará,Rua 76 do Estado Ceará,239.0,Apto 19
65,65,2018-02-06 05:56:36,Willian,Freitas,NaN,9 3043-7382,Brasil,Rio de Janeiro,Rua 91 do Estado Rio de Janeiro,96.0,Apto 7
68,68,2018-11-14 11:04:35,José,Pires,josé@usuario.com,9 8189-2149,Brasil,Ceará,Avenida 99 do Estado Ceará,231.0,NaN
77,77,2018-11-30 10:29:55,Ana,Monteiro,ana@teste.com,9 3871-4132,Brasil,Bahia,Praça 86 do Estado Bahia,604.0,Apto 30
88,88,2017-10-12 15:17:05,Rafael,Batista,rafael@usuario.com,9 8656-5668,Brasil,Ceará,Rua 78 do Estado Ceará,787.0,Apto 3
89,89,2017-12-07 19:24:54,Daniela,Pires,daniela@usuario.com,9 6666-2265,Brasil,Bahia,Rua 31 do Estado Bahia,441.0,NaN